#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

bspc config border_width         1
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -r "*"
bspc rule -a "*" desktop='^10'
bspc rule -a code desktop='^2'
bspc rule -a firefox desktop='^3'
bspc rule -a Alacritty desktop='^1'
bspc rule -a vlc desktop='^4'
bspc rule -a Thunar desktop='^5'
bspc rule -a Spotify desktop='^8'
bspc rule -a TelegramDesktop desktop='^9'
bspc rule -a Whatsapp-for-linux desktop='^9'
bspc rule -a Virt-manager desktop='^6'
bspc rule -a Protonvpn desktop='^7' state=floating

feh --bg-scale --randomize $HOME/.wallapers/
$HOME/.config/polybar/launch.sh
picom -b
